// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRnCeeDvUiIc7D8-Nf4oBLjyMObf_tLI0',
    appId: '1:639712765365:web:4755dd5cf2f51d9bca65fc',
    messagingSenderId: '639712765365',
    projectId: 'airventure-da32a',
    authDomain: 'airventure-da32a.firebaseapp.com',
    storageBucket: 'airventure-da32a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuL_rQXCcUJ08USw11jcQsHS_KZbmHmgQ',
    appId: '1:639712765365:android:de66c9df5718a5c3ca65fc',
    messagingSenderId: '639712765365',
    projectId: 'airventure-da32a',
    storageBucket: 'airventure-da32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA00BMikY7SiubuS_7Hil_R1NLy9tuknvU',
    appId: '1:639712765365:ios:89a2af05d1842211ca65fc',
    messagingSenderId: '639712765365',
    projectId: 'airventure-da32a',
    storageBucket: 'airventure-da32a.appspot.com',
    iosClientId: '639712765365-it5m2eiku9rt3lr6ov48d257hjak3dmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hawaiJubu',
  );
}
